### PR TITLE
Adds CTP

### PR DESCRIPTION
**Pull request by Rishi556**

### CODE REVIEW

**Comment by feruzm** [comment]
Could you please give some post examples?

**Comment by Rishi556** [comment]
https://www.ctptalk.com/neoxian/@dkid14/relax-and-have-some-fun-win-10-hive-and-some-upvotes

**Comment by feruzm** [comment]
> https://www.ctptalk.com/neoxian/@dkid14/relax-and-have-some-fun-win-10-hive-and-some-upvotes

Hmm edited with peakd it seem, I cannot see app field in json_metadata of the post.

**Comment by Rishi556** [comment]
{"app":"clicktrackprofit\/0.1","canonical_url":"https:\/\/www.ctptalk.com\/@rishi556\/q9iht6"}

https://hiveblocks.com/ctp/@rishi556/q9iht6

**Review by feruzm — APPROVED** [review]

**Pull request merged**
